export const mockApiGatewayEvent = {
  body: null,
  headers: {},
  multiValueHeaders: {},
  httpMethod: "string",
  isBase64Encoded: true,
  path: "string",
  pathParameters: null,
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  stageVariables: null,
  requestContext: {
    accountId: "string",
    apiId: "string",
    authorizer: {},
    protocol: "string",
    httpMethod: "string",
    identity: {
      accessKey: "string",
      accountId: "string",
      apiKey: "string",
      apiKeyId: "string",
      caller: "string",
      clientCert: null,
      cognitoAuthenticationProvider: "string",
      cognitoAuthenticationType: "string",
      cognitoIdentityId: "string",
      cognitoIdentityPoolId: "string",
      principalOrgId: "string",
      sourceIp: "string",
      user: "string",
      userAgent: "string",
      userArn: "string",
    },
    path: "string",
    stage: "string",
    requestId: "string",
    requestTimeEpoch: 1,
    resourceId: "string",
    resourcePath: "string",
  },
  resource: "string",
};
